sudo: required
language: python
python:
  - 3.6
services:
  - docker

jobs:
  include:
    - stage: Build Docker Images
      script:
        - travis_wait 120 sleep infinity & $TRAVIS_BUILD_DIR/build.sh
    - stage: Deploy Docker Images to Docker Hub
      if: type != pull_request AND (branch = master OR tag IS present)
      script:
        - travis_wait 120 sleep infinity & $TRAVIS_BUILD_DIR/distribute.sh

env:
  global:
    secure: c5WCROhJdrdpP7eAfKxirqStVK8lBxm0Wzm8m2EzPxqaFyjBeRZcl/ox01x9xXXqnCRklalmxP/6qLpPWiexUU26o7SKNunSkVjmqPMpAVlBDB5fnEIjJCzDH84ATVGj0da5bCgbstTj9Xmq12VoIBVcRBPMWL1wIiSeyB6Jpp/509M+UamMMZzM73BydOArOIU4ioR8k+3ZfJ7dD+3JYeeriltwwb63XyTq1jBD4pypTPbOBuuhYdTO5Pe2tF6jnIzoQwPHnjE0PRsv4+N3HAMAZV3CLoPPdLFFC7m2yltKN42URBWavLV/zGfDUnxOMB9VEr/lxuQ84s6oj9HS17nUs3nHQG+mA2r4UH4FkzmszDeyNGH+t4O7GjnN8gWQQTY5FkPUy3S0MVjfyipGCrpgEc4GGwSlthEtXeMHyVe4G8DXZUy+44VLsI3dUJLX2rIW8Obs3p2RFDfz4hoCORWAW+35kfdtbgeWfxDHlPx2US0rYnkVy4d8L/xVj3NYU2OuWWeY++hadbHgutc8y/Ckh30EAGGOsfBz7s6YAHlHWPv9fkxBRnV45/iZqaFrweISKYa5uJZPsBo+kjaUrgOoeDZhJ/xL7YStEElFS4TO6c/sLO4UwNG+sS8/WWjilFmO0kkDDO76PZgZDQkf7ECahS89MKrlULluZVlRJRo=
notifications:
  slack:
    secure: rboavN/AjVVGFmH25UT4aW6RkvvP/h6UN1tZZQWArgzjnxTmqUNYyRRdTc17rEMOCfYDZ8Q/Z+Tx5jiXYQpOYhJLMC7tNsi92iEpq4ELBh1FwAW3FnR9Z1uDxsrjPvvXqxNzqpSXwLx+xYRLbbR2Q82Oy1MDLz1Uu+500kx2D5AeeTeItaXzM42+JcbSEEsv3L6BdUdt45jBAGjP/w7SqYScl4axS/Q7z78b71Fel8VDrDkdzfJVp28FeoNKKyhEpioms03IiXKAd0Gf1hZKvy6ta4RpmWA7m31GYDjLuLoi7C/+AEUgNK5ENMnTl8ZffAxGlyP/+0/jDmlV0NQs7hcXULr4Kx24iXbvvlhZXlmKIlAuMVlUtlQ4T1g4IbXyTwA0KMRF7OCQJwfU3pKV/OrPpk++Dd1QdXrIy2X1ffnTYPsXhauBzNPMX8grqWedeZKqaYb7YL+AhBW+tZNiW6mQ+4ssd/CCUqddeDULHpOljjEOLtmPF4fvbEypJM9DsXZfNXyUyensccjG/5iByNqTShOq9c4ns2+8vtiV0FIBnTyrfPK2rWpjZIeL3NAVsEWepMGmaLy3Y1vb0NHStPU8X4gsdgvPcVHwBGo8aUXof+2ImsrYKXFmtPRQj1fI+MrcDjxy0GsAnUzsCqDSiamVOyotJ+DCf5tOzA/iJiQ=
