# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Zigbee2MQTT Proxy
version: "1.0.0"
breaking_versions:
  - "1.0.0"
slug: zigbee2mqtt_proxy
description: Proxy for externally running Zigbee2MQTT
url: "https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt-proxy"
panel_icon: "mdi:zigbee"
arch:
  - aarch64
  - amd64
image: "ghcr.io/zigbee2mqtt/zigbee2mqtt-proxy-{arch}"
init: false
ingress: true
timeout: 30
map:
  - addon_config:rw
ports:
  "8099/tcp": null
options:
  server: ""
  auth_token: ""
schema:
  server: url
  auth_token: "str?"
